spring:
  application:
    name: max-integer-solver
    title: max-integer-solver
  h2:
    console:
      enabled: true
  datasource-postgresql:
    url: jdbc:postgresql://localhost:5432/CastorEmployees
    driverClassName: "org.postgresql.Driver"
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  servlet:
    context-path: /api/v1

springdoc:
  show-actuator: true
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include:  openapi, swagger-ui

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
